const res = 
{
  "Bg3": "./games/protect-radish/images/Bg3.png",
  "Bg4": "./games/protect-radish/images/Bg4.png",
  "CloseNormal": "./games/protect-radish/images/CloseNormal.png",
  "CloseSelected": "./games/protect-radish/images/CloseSelected.png",
  "json_BatteryDt": "./games/protect-radish/images/Data/BatteryDt.json",
  "json_BulletDt": "./games/protect-radish/images/Data/BulletDt.json",
  "json_CardDt": "./games/protect-radish/images/Data/CardDt.json",
  "json_EffectDt": "./games/protect-radish/images/Data/EffectDt.json",
  "json_MapData": "./games/protect-radish/images/Data/MapData.json",
  "json_MonsterDt": "./games/protect-radish/images/Data/MonsterDt.json",
  "json_ResData": "./games/protect-radish/images/Data/ResData.json",
  "json_SelLevel": "./games/protect-radish/images/Data/SelLevel.json",
  "json_obstaclesDt": "./games/protect-radish/images/Data/obstaclesDt.json",
  "json_propsData": "./games/protect-radish/images/Data/propsData.json",
  "Default-Landscape~ipad": "./games/protect-radish/images/Default-Landscape~ipad.png",
  "HelloWorld": "./games/protect-radish/images/HelloWorld.png",
  "Item1": "./games/protect-radish/images/Item1.png",
  "Item2": "./games/protect-radish/images/Item2.png",
  "Item3": "./games/protect-radish/images/Item3.png",
  "Item4": "./games/protect-radish/images/Item4.png",
  "sucai": "./games/protect-radish/images/sucai.png",
  "sucai2": "./games/protect-radish/images/sucai2.png",
  "json_ui_Battery": "./games/protect-radish/images/ui_Battery.json",
  "ui_Battery": "./games/protect-radish/images/ui_Battery.png",
  "json_ui_Item": "./games/protect-radish/images/ui_Item.json",
  "ui_Item": "./games/protect-radish/images/ui_Item.png",
  "json_ui_Menu": "./games/protect-radish/images/ui_Menu.json",
  "ui_Menu": "./games/protect-radish/images/ui_Menu.png",
  "json_ui_Monster": "./games/protect-radish/images/ui_Monster.json",
  "ui_Monster": "./games/protect-radish/images/ui_Monster.png",
  "ui_ProgressBar_01": "./games/protect-radish/images/ui_ProgressBar_01.png",
  "ui_ProgressBar_02": "./games/protect-radish/images/ui_ProgressBar_02.png",
  "json_ui_Select": "./games/protect-radish/images/ui_Select.json",
  "ui_Select": "./games/protect-radish/images/ui_Select.png",
  "json_ui_luobo": "./games/protect-radish/images/ui_luobo.json",
  "ui_luobo": "./games/protect-radish/images/ui_luobo.png",
  "json_ui_obstacle": "./games/protect-radish/images/ui_obstacle.json",
  "ui_obstacle": "./games/protect-radish/images/ui_obstacle.png"
};
export default res;